on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        id: ["windows", "android"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: "3.13.9"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - if: ${{matrix.id == 'android'}}
        name: Build APK
        run: flutter build apk

      - name: PWD
        run: echo $pwd
      - name: List dirs/files
        run: ls
      - name: List dirs/files windows
        run: ls windows

      - if: ${{matrix.id == 'windows'}}
        name: Build Windows
        run: flutter build windows
      - if: ${{matrix.id == 'windows'}}
        name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: windows/inno_installer.iss
          options: /Qp

      - if: ${{matrix.id == 'windows'}}
        name: Create Release Windows
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/windows/workflow_test_install.exe"

      - if: ${{matrix.id == 'android'}}
        name: Create Release Android
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/apk/release/app-release.apk"
