on:
  push:
    tags:
      - "*"

jobs:
  frontend-release-android:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: "3.13.9"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Create Release Android
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "frontend/build/app/outputs/apk/release/app-release.apk"

  frontend-release-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      # - name: Fix pubspec
      #   run: python update_pubspec.py ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: "3.13.9"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: frontend/windows/inno_installer.iss
          options: /Qp

      - name: Create Release Windows
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "frontend/build/windows/workflow_test_install.exe"

  backend-release-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: dart pub get

      - name: Build
        run: dart compile exe -o server.exe bin/server.dart

      - name: Create Release Server
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "backend/server.exe"
